-- MySQL Script generated by MySQL Workbench
-- Mon Oct 16 01:24:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hotel` ;

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `hotel`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `cpf` VARCHAR(20) NULL,
  `endereco` VARCHAR(50) NULL,
  `tipo_pessoa` CHAR(1) NULL COMMENT 'F - Funcionário \nC - Cliente',
  `email` VARCHAR(50) NULL,
  `recebeNotificacao` VARCHAR(2) NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`tipo_quarto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`tipo_quarto` ;

CREATE TABLE IF NOT EXISTS `hotel`.`tipo_quarto` (
  `id` INT NOT NULL,
  `nome` VARCHAR(50) NULL,
  `valor` FLOAT NULL,
  `max_pessoas` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`quarto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`quarto` ;

CREATE TABLE IF NOT EXISTS `hotel`.`quarto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NULL DEFAULT NULL,
  `estado` VARCHAR(20) NULL DEFAULT NULL,
  `tipo_quarto_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quarto_tipo_quarto_idx` (`tipo_quarto_id` ASC),
  CONSTRAINT `fk_quarto_tipo_quarto`
    FOREIGN KEY (`tipo_quarto_id`)
    REFERENCES `hotel`.`tipo_quarto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`reserva` ;

CREATE TABLE IF NOT EXISTS `hotel`.`reserva` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT NULL DEFAULT NULL,
  `quarto_id` INT NULL DEFAULT NULL,
  `data_checkin` VARCHAR(10) NULL DEFAULT NULL,
  `data_checkout` VARCHAR(10) NULL DEFAULT NULL,
  `data_reserva` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reserva_pessoa1_idx` (`pessoa_id` ASC),
  INDEX `fk_reserva_quarto1_idx` (`quarto_id` ASC),
  CONSTRAINT `fk_reserva_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `hotel`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_quarto1`
    FOREIGN KEY (`quarto_id`)
    REFERENCES `hotel`.`quarto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
